keys:
  - hosts:
      - &scorpius_cl_01 age18jjzz654zck4yuna87w895tzyn803junh5aup9u7ppkjf5zppqgqefp57t
    users:
      - &cyril_at_scorpius age148jrkzdhyv0eq985fg6gyexsgnv3ud4z3s453nkdat9hl2879cuqrt6pmn
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    mac_only_encrypted: true
    key_groups:
      - age:
          - *scorpius_cl_01
          - *cyril_at_scorpius
